# Pre-commit hooks for Kalshi Market Insights
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

default_language_version:
  python: python3.11

repos:
  # General hooks for all files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^frontend/pnpm-lock\.yaml$
      - id: end-of-file-fixer
        exclude: ^frontend/pnpm-lock\.yaml$
      - id: check-yaml
        args: [--unsafe]  # Allow custom YAML tags
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-json
        exclude: tsconfig.*\.json$
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  # Python: Ruff (linting + formatting, replaces Black and Flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      # Run linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^backend/
      # Run formatter
      - id: ruff-format
        files: ^backend/

  # Python: Type checking with mypy
  # Runs from backend directory where package is installed via wrapper script
  - repo: local
    hooks:
      - id: mypy
        name: mypy type checking
        entry: .githooks/run-mypy.sh
        language: script
        types: [python]
        files: ^backend/
        pass_filenames: false
        require_serial: true

  # Frontend: ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^frontend/src/.*\.[jt]sx?$
        types: [file]
        args: [--fix, --max-warnings=0]
        additional_dependencies:
          - eslint@8.56.0
          - '@typescript-eslint/eslint-plugin@6.21.0'
          - '@typescript-eslint/parser@6.21.0'
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-refresh@0.4.5
          - typescript@5.3.3

  # Frontend: Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/.*\.(ts|tsx|js|jsx|json|css|md)$
        exclude: ^frontend/pnpm-lock\.yaml$
        additional_dependencies:
          - prettier@3.2.5

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3013]

  # Security: Check for secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package.lock.json|pnpm-lock.yaml
